module Numerical
  class Constants
    NUMBERS = {
      "zero"      => 0,
      "one"       => 1,
      "two"       => 2,
      "three"     => 3,
      "four"      => 4,
      "five"      => 5,
      "six"       => 6,
      "seven"     => 7,
      "eight"     => 8,
      "nine"      => 9,
      "ten"       => 10,
      "eleven"    => 11,
      "twelve"    => 12,
      "thirteen"  => 13,
      "fourteen"  => 14,
      "fifteen"   => 15,
      "sixteen"   => 16,
      "seventeen" => 17,
      "eighteen"  => 18,
      "nineteen"  => 19,
      "twenty"    => 20,
      "thirty"    => 30,
      "forty"     => 40,
      "fifty"     => 50,
      "sixty"     => 60,
      "seventy"   => 70,
      "eighty"    => 80,
      "ninety"    => 90,
    }.freeze

    SHORT_FORM = {
      "thousand"          => 1000 ** 1,
      "million"           => 1000 ** 2,
      "billion"           => 1000 ** 3,
      "trillion"          => 1000 ** 4,
      "quadrillion"       => 1000 ** 5,
      "quintillion"       => 1000 ** 6,
      "sextillion"        => 1000 ** 7,
      "septillion"        => 1000 ** 8,
      "octillion"         => 1000 ** 9,
      "nonillion"         => 1000 ** 10,
      "decillion"         => 1000 ** 11,
      "undecillion"       => 1000 ** 12,
      "duodecillion"      => 1000 ** 13,
      "tredecillion"      => 1000 ** 14,
      "quattuordecillion" => 1000 ** 15,
      "quindecillion"     => 1000 ** 16,
      "sexdecillion"      => 1000 ** 17,
      "septendecillion"   => 1000 ** 18,
      "octodecillion"     => 1000 ** 19,
      "novemdecillion"    => 1000 ** 20,
      "vigintillion"      => 1000 ** 21,
    }.freeze
  end
end